version: '3.8'

#name: mlops-services

services:
  mlflow:
    build:
      context: .
      dockerfile: mlflow.Dockerfile
    image: mlflow-server:v0.1
    container_name: mlflow_server
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID = ${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY = ${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION = ${AWS_DEFAULT_REGION}
    ports:
      - 5000:5000
    #command: mlflow server --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${MLFLOW_DB} --default-artifact-root /mlflow/artifacts --host 0.0.0.0 
    # Command to launch MLflow server pointing to a local storage for artifacts
    command: >
      mlflow server 
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB} 
      --host 0.0.0.0 
      --port 5000
      --artifacts-destination s3://jvaa-mlflow-artifacts
      --serve-artifacts
  